dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
dotenv: .env
networks:
  default: development
  rinkeby: active
wallets:
  from_key: ${PRIVATE_KEY}
